import {
  defineInvitationThemePackage,
  FULL_INVITATION_THEME_CAPABILITIES,
} from '../core/theme-package.types';

import { RoselleTemplate } from './roselle-template';

export const roselleThemePackage = defineInvitationThemePackage({
  defaultPaletteKey: 'rose',
  manifest: {
    badge: 'Soft romance',
    capabilities: FULL_INVITATION_THEME_CAPABILITIES,
    description: 'Botanical, hangat, dan terasa seperti surat personal untuk setiap tamu.',
    featured: true,
    key: 'roselle',
    mood: 'Botanical softness · warm editorial · intimate rhythm',
    moods: ['soft', 'warm', 'romantic'],
    motif: '/marketing/roselle-botanical-line.svg',
    name: 'Roselle',
    parity: {
      coupleAnchorId: 'roselle-couple-title',
      experienceHook: 'data-roselle-experience',
      experienceValue: 'letter-v1',
      greetingAnchorId: 'roselle-personal-greeting',
      identity: 'intimate-romantic-letter',
      invitationTitleId: 'roselle-invitation-title',
    },
    personality: 'Romantic editorial',
    preview: {
      date: '17 Agustus 2027',
      eyebrow: 'The wedding of',
      guestLine: 'Undangan personal telah disiapkan untuk',
      guestName: 'Bapak Aditya & Keluarga',
      stageLabel: 'Romantic warmth',
    },
    styles: ['romantic', 'editorial', 'botanical'],
  },
  palettes: [
    {
      accent: '#8e4b52',
      canvas: '#f2dedd',
      ink: '#3d2d31',
      key: 'rose',
      name: 'Rose',
      paper: '#fffaf7',
      soft: '#dcb9b6',
      swatch: '#b96872',
      variables: {
        '--roselle-ivory': '#fffaf4',
        '--roselle-paper': '#fffefb',
        '--roselle-plum': '#402b35',
        '--roselle-plum-soft': '#68545c',
        '--roselle-mauve': '#97636d',
        '--roselle-rose': '#bd7d83',
        '--roselle-sage': '#718373',
        '--roselle-line': '#e6d6ca',
        '--roselle-wash': '#f7ece7',
        '--roselle-wash-deep': '#f2e2dc',
      },
    },
    {
      accent: '#5f7562',
      canvas: '#e2eadf',
      ink: '#2f3d33',
      key: 'sage',
      name: 'Sage',
      paper: '#fbfcf7',
      soft: '#b7c9b5',
      swatch: '#7d9a7f',
      variables: {
        '--roselle-ivory': '#f7fbf3',
        '--roselle-paper': '#fcfdf8',
        '--roselle-plum': '#2f3d33',
        '--roselle-plum-soft': '#58665b',
        '--roselle-mauve': '#5f7562',
        '--roselle-rose': '#90aa8e',
        '--roselle-sage': '#637b66',
        '--roselle-line': '#d4e0d1',
        '--roselle-wash': '#e9f1e5',
        '--roselle-wash-deep': '#dce8d8',
      },
    },
    {
      accent: '#a66b35',
      canvas: '#f5e8c9',
      ink: '#4a3725',
      key: 'butter',
      name: 'Butter',
      paper: '#fffdf5',
      soft: '#dfc786',
      swatch: '#d5ae54',
      variables: {
        '--roselle-ivory': '#fffaf0',
        '--roselle-paper': '#fffdf7',
        '--roselle-plum': '#4a3725',
        '--roselle-plum-soft': '#715c43',
        '--roselle-mauve': '#a66b35',
        '--roselle-rose': '#d5ae54',
        '--roselle-sage': '#8c7c53',
        '--roselle-line': '#eadab4',
        '--roselle-wash': '#f8edcf',
        '--roselle-wash-deep': '#f1dfb2',
      },
    },
    {
      accent: '#783c54',
      canvas: '#ead9e2',
      ink: '#3f2832',
      key: 'berry',
      name: 'Berry',
      paper: '#fff9fc',
      soft: '#c49aad',
      swatch: '#96546f',
      variables: {
        '--roselle-ivory': '#fff8fc',
        '--roselle-paper': '#fffafd',
        '--roselle-plum': '#3f2832',
        '--roselle-plum-soft': '#69505b',
        '--roselle-mauve': '#783c54',
        '--roselle-rose': '#a85f7c',
        '--roselle-sage': '#80706f',
        '--roselle-line': '#e4ccd8',
        '--roselle-wash': '#f2e3eb',
        '--roselle-wash-deep': '#ead5e0',
      },
    },
  ],
  Renderer: RoselleTemplate,
});
