import {
  defineInvitationThemePackage,
  FULL_INVITATION_THEME_CAPABILITIES,
} from '../core/theme-package.types';

import { RoselleTemplate } from './roselle-template';

export const roselleThemePackage = defineInvitationThemePackage({
  defaultPaletteKey: 'rose',
  manifest: {
    badge: 'Soft romance',
    capabilities: FULL_INVITATION_THEME_CAPABILITIES,
    description: 'Botanical, hangat, dan terasa seperti surat personal untuk setiap tamu.',
    featured: true,
    key: 'roselle',
    mood: 'Botanical softness · warm editorial · intimate rhythm',
    moods: ['soft', 'warm', 'romantic'],
    motif: '/marketing/roselle-botanical-line.svg',
    name: 'Roselle',
    parity: {
      coupleAnchorId: 'roselle-couple-title',
      experienceHook: 'data-roselle-experience',
      experienceValue: 'letter-v1',
      greetingAnchorId: 'roselle-personal-greeting',
      identity: 'intimate-romantic-letter',
      invitationTitleId: 'roselle-invitation-title',
    },
    personality: 'Romantic editorial',
    preview: {
      date: '17 Agustus 2027',
      eyebrow: 'The wedding of',
      guestLine: 'Undangan personal telah disiapkan untuk',
      guestName: 'Bapak Aditya & Keluarga',
      stageLabel: 'Romantic warmth',
    },
    styles: ['romantic', 'editorial', 'botanical'],
  },
  palettes: [
    {
      accent: '#8e4b52',
      canvas: '#f2dedd',
      ink: '#3d2d31',
      key: 'rose',
      tokens: {
        accent: '#97636d',
        border: '#e6d6ca',
        canvas: '#fffaf4',
        highlight: '#bd7d83',
        ink: '#402b35',
        muted: '#68545c',
        secondary: '#718373',
        surface: '#fffefb',
        wash: '#f7ece7',
      },
      name: 'Rose',
      paper: '#fffaf7',
      soft: '#dcb9b6',
      swatch: '#b96872',
    },
    {
      accent: '#5f7562',
      canvas: '#e2eadf',
      ink: '#2f3d33',
      key: 'sage',
      tokens: {
        accent: '#5f7562',
        border: '#b7c9b5',
        canvas: '#e2eadf',
        highlight: '#7d9a7f',
        ink: '#2f3d33',
        muted: '#657268',
        secondary: '#8e6e78',
        surface: '#fbfcf7',
        wash: '#d5e2d2',
      },
      name: 'Sage',
      paper: '#fbfcf7',
      soft: '#b7c9b5',
      swatch: '#7d9a7f',
    },
    {
      accent: '#a66b35',
      canvas: '#f5e8c9',
      ink: '#4a3725',
      key: 'butter',
      tokens: {
        accent: '#a66b35',
        border: '#dfc786',
        canvas: '#f5e8c9',
        highlight: '#d5ae54',
        ink: '#4a3725',
        muted: '#725b43',
        secondary: '#7b8158',
        surface: '#fffdf5',
        wash: '#f0dfaf',
      },
      name: 'Butter',
      paper: '#fffdf5',
      soft: '#dfc786',
      swatch: '#d5ae54',
    },
    {
      accent: '#783c54',
      canvas: '#ead9e2',
      ink: '#3f2832',
      key: 'berry',
      tokens: {
        accent: '#783c54',
        border: '#c49aad',
        canvas: '#ead9e2',
        highlight: '#96546f',
        ink: '#3f2832',
        muted: '#705563',
        secondary: '#718373',
        surface: '#fff9fc',
        wash: '#e2c9d5',
      },
      name: 'Berry',
      paper: '#fff9fc',
      soft: '#c49aad',
      swatch: '#96546f',
    },
  ],
  Renderer: RoselleTemplate,
});
