import {
  defineInvitationThemePackage,
  FULL_INVITATION_THEME_CAPABILITIES,
} from '../core/theme-package.types';

import { ArunaTemplate } from './aruna-template';

export const arunaThemePackage = defineInvitationThemePackage({
  defaultPaletteKey: 'stone',
  manifest: {
    badge: 'Gen Z editorial',
    capabilities: FULL_INVITATION_THEME_CAPABILITIES,
    description: 'Grid bersih, tipografi tegas, dan komposisi yang terasa seperti wedding zine.',
    featured: true,
    key: 'aruna',
    mood: 'Editorial grid · directional type · refined contrast',
    moods: ['modern', 'cool', 'expressive'],
    motif: '/marketing/aruna-editorial-grid.svg',
    name: 'Aruna',
    parity: {
      coupleAnchorId: 'aruna-couple-title',
      experienceHook: 'data-aruna-experience',
      experienceValue: 'journal-v1',
      greetingAnchorId: 'aruna-personal-greeting',
      identity: 'modern-wedding-journal',
      invitationTitleId: 'aruna-invitation-title',
    },
    personality: 'Modern wedding journal',
    preview: {
      date: 'Jakarta · 17.08.27',
      eyebrow: 'Wedding journal · 017',
      guestLine: 'Personal edition prepared for',
      guestName: 'Aditya & Family',
      stageLabel: 'Modern editorial',
    },
    styles: ['editorial', 'modern', 'minimal'],
  },
  palettes: [
    {
      accent: '#59625d',
      canvas: '#e7e5dc',
      ink: '#252a27',
      key: 'stone',
      tokens: {
        accent: '#59625d',
        border: '#b9b9ae',
        canvas: '#e7e5dc',
        highlight: '#757c77',
        ink: '#252a27',
        muted: '#6a6f6b',
        secondary: '#8c6a58',
        surface: '#f8f7f2',
        wash: '#dedcd3',
      },
      name: 'Stone',
      paper: '#f8f7f2',
      soft: '#b9b9ae',
      swatch: '#757c77',
    },
    {
      accent: '#63764e',
      canvas: '#e6ead7',
      ink: '#303827',
      key: 'matcha',
      tokens: {
        accent: '#63764e',
        border: '#b9c797',
        canvas: '#e6ead7',
        highlight: '#80945f',
        ink: '#303827',
        muted: '#68705b',
        secondary: '#9b6a4e',
        surface: '#fafbf3',
        wash: '#d9e1c1',
      },
      name: 'Matcha',
      paper: '#fafbf3',
      soft: '#b9c797',
      swatch: '#80945f',
    },
    {
      accent: '#315b9b',
      canvas: '#dce7f7',
      ink: '#20334e',
      key: 'cobalt',
      tokens: {
        accent: '#315b9b',
        border: '#94afd7',
        canvas: '#dce7f7',
        highlight: '#4778bf',
        ink: '#20334e',
        muted: '#62728a',
        secondary: '#9b6153',
        surface: '#f8fbff',
        wash: '#cdddf3',
      },
      name: 'Cobalt',
      paper: '#f8fbff',
      soft: '#94afd7',
      swatch: '#4778bf',
    },
    {
      accent: '#a95f42',
      canvas: '#f3dfd2',
      ink: '#4a3026',
      key: 'apricot',
      tokens: {
        accent: '#a95f42',
        border: '#d7a086',
        canvas: '#f3dfd2',
        highlight: '#c97b59',
        ink: '#4a3026',
        muted: '#795b50',
        secondary: '#6f7463',
        surface: '#fffaf6',
        wash: '#efd1c0',
      },
      name: 'Apricot',
      paper: '#fffaf6',
      soft: '#d7a086',
      swatch: '#c97b59',
    },
  ],
  Renderer: ArunaTemplate,
});
